### PR TITLE
Fix style svg

### PR DESCRIPTION
**Pull request by galkatz373**
#345 
Remove CSSProperties from the style of the svg, and replace it with a string.

### CODE REVIEW

**Comment by jasonlyu123** [comment]
Can you also remove the CSSProperties from element?

**Comment by galkatz373** [comment]
Do we even need the interface? i'm not sure the purpose of it

**Comment by jasonlyu123** [comment]
I'm ok with remove the interface

**Comment by dummdidumm** [comment]
Yeah we should remove it, this is react-specific stuff.

**Comment by dummdidumm** [comment]
Thanks! The shim is a whole lot smaller now, I like!

**Pull request merged**
