### PR TITLE
(feat) TypeScript Inlay Hint

### PR DESCRIPTION
**Pull request by jasonlyu123**
#1336

This is not enabled by default. You'll have to enable it with the TypeScript inlay hints configs of VSCode. There are multiple configs under `javascript.inlayHints.*` and `typescript.inlayHints.*`. Enable them based on your preference. 

## implementation detail
The test is set up similarly to the diagnostics snapshot test. You can also run `yarn test --debug` to output `debug.svelte` with inlay hints added to the original file as comments. for example:

```svelte
<script lang="ts">
    import { SvelteComponentTyped } from 'svelte';

    let Component: typeof SvelteComponentTyped;
    function hi(name: string)/* : void*/ {}
</script>

<Component text={hi(/*name: */'')}></Component>
``` 

## Screenshots

圖片
圖片

(enable all inlay hints options is really just too much for my taste lol)

### CODE REVIEW

**Review by dummdidumm — APPROVED** [review]
Damn, this is impressive work - thank you so much!

**Comment by polyzen** [comment]
Is this also available via `svelte.plugin.typescript.inlayHints.enable`? Not listed in the readme. Would like to use this in Neovim.

**Comment by dummdidumm** [comment]
This uses the VSCode TypeScript options to enable it. How does Neovim enable it for TS (through which option(s))?

**Comment by polyzen** [comment]
> This uses the VSCode TypeScript options to enable it. How does Neovim enable it for TS (through which option(s))?

https://github.com/lvimuser/lsp-inlayhints.nvim#typescript

**Comment by aidenlangley** [comment]
https://github.com/sveltejs/language-tools/issues/1895

Neovim doesn't handle any of the workspace/something/refresh requests right now. Need this to be configurable please.

**Comment by dummdidumm** [comment]
@polyzen you can read about the settings here: https://github.com/sveltejs/language-tools/tree/master/packages/language-server#settings , settings references are linked

**Comment by GustavoJCL** [comment]
How can I enable it on neovim? Neovim 0.10 now have built-in inlay hints

**Pull request merged**
