### PR TITLE
(fix) register OnEnter rules (#236)

### LINKED ISSUE #236: Svelte VSCode doesn't register OnEnter Rules for indentation
**Describe the bug**
The VSCode extension doesn't register OnEnter rules for auto indentation.

**To Reproduce**

Pressing enter with the cursor (`|`) here:
```html
<div>|</div>
```
Produces this
```html
<div>
|</div>
```

**Expected behavior**
Pressing enter with the cursor (`|`) here:
```html
<div>|</div>
```
Should produce this (assuming 2 space indentation setting)
```html
<div>
  |
</div>
```

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - IDE: VSCode
 - Plugin/Package: https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

**Additional context**
I patched the extension copy pasting the code from the HTML extension snippet below and it fixed the problem.

https://github.com/microsoft/vscode/blob/04c36be045a94fee58e5f8992d3e3fd980294a84/extensions/html-language-features/client/src/htmlClient.ts#L209-L226

### PR DESCRIPTION
**Pull request by b-fuze**
Register OnEnter rules for proper auto indenting. Fixes #236

### CODE REVIEW

**Comment by b-fuze** [comment]
All the lint errors seem to be related to the very long regex used in the OnEnter rules. Should I make eslint ignore those errors or attempt to fix it somehow?

**Comment by orta** [comment]
hah, yeah, I'd make eslint disable the line completely

**Comment by dummdidumm** [comment]
Thanks for the PR! Could you for each regex add a short comment roughly explaining what it does?

**Comment by b-fuze** [comment]
@dummdidumm I actually copied it mostly verbatim from https://github.com/microsoft/vscode/blob/master/extensions/html-language-features/client/src/htmlClient.ts#L209-L226

Should I write a short comment explaining how I understand it?

**Comment by dummdidumm** [comment]
That would be great!

**Comment by b-fuze** [comment]
@dummdidumm @orta Done

**Comment by dummdidumm** [comment]
👍

**Pull request merged**
