### PR TITLE
(feat) Sapper: shim `this` inside preload function

### PR DESCRIPTION
**Pull request by dummdidumm**
#497 

Question:
- Don't care about detection and just do the transformation either way? --> Yes, don't care for now, too much of an edge case to care for it

Side note:
- Found a source map bug during this when only `<script context="module">` is present?

### CODE REVIEW

**Comment by jasonlyu123** [comment]
I think we can add some check if the user has already type `this` in the preload function
```ts
interface PreloadContext {
    fetch: (url: string, options?: any) => Promise<any>;
    error: (statusCode: number, error: any) => void;
    redirect: (statusCode: number, location: string) => Promise<any>;
}
export function preload(this: PreloadContext) {})
```

**Comment by dummdidumm** [comment]
Good point, did not think about that. We could also make this the proposed solution to get proper typing without baking it into the language tools.

@benmccann what do you think about this? Is it feasible/better to add typings for the `this`-context and the other `preload` arguments to the Sapper typings and instruct people in the docs to use those when they want to use `preload` in TypeScript projects?

**Comment by benmccann** [comment]
One thing to note is that the Sapper preload context may become user-modifiable along the lines of https://github.com/sveltejs/sapper/pull/1336

It does seem like language-tools shouldn't need to know about Sapper specifically. Though the current way for the user to do this is really ugly: https://github.com/babichjacob/sapper-typescript-graphql-template/issues/19#issuecomment-683362969. I'm not quite sure what the best way to improve this would be.

**Comment by dummdidumm** [comment]
@benmccann thanks for the issue links. This makes me think even more that we should not know about this `this` (hah).

As mentioned in my comment above, the best way IMO would be to provide typings for the standard context and the preload/session parameters:

````html
<script context="module">
    import type { PreloadContext, PreloadPage, PreloadSession } from "@sapper/preload";

    export async function preload(this: PreloadContext, page: PreloadPage, session: PreloadSession) {
       ...
       this.fetch(...) // <-- works without type errors
    }
</script>
```

If you tell me where to put them I'm happy to open a PR with those types over at the Sapper repo.

**Pull request closed without merging**
