### PR TITLE
(fix) generic support for component getter and accessor

### PR DESCRIPTION
**Pull request by jasonlyu123**
#1688

### CODE REVIEW

**Comment by dummdidumm** [comment]
Do you know why we don't transform getters by doing `get foo() { return this.$$prop_def.foo }`? This should work the same for components with and without generics.

**Comment by dummdidumm** [comment]
Mhm, maybe (I thought $$prop_def always existed, but my memory might be tricking me 😅 ). Either way, if there's nothing speaking against it, I'd say it's probably better to transform it that way now, which would make special code for the generic case unnecessary. What do you think?

**Comment by dummdidumm** [comment]
mhhm I think we can probably remove `getters` from the transpiled output then. We can't remove `this.getters` from `ExportedNames` though because that's used to distinguish between props that are writeable (`export let ..`) and those that are only readable (`export const/function ..`)

**Comment by dummdidumm** [comment]
Nice one! Is this ready to merge?

**Comment by jasonlyu123** [comment]
It's ready. Any other thing you want to change?

**Review by dummdidumm — APPROVED** [review]

**Pull request merged**
