### PR TITLE
fix: support default parameter in snippet block

### PR DESCRIPTION
**Pull request by jasonlyu123**
#2384

### CODE REVIEW

**Comment by jasonlyu123** [comment]
Still need to find a way to infer the type from the default value.

**Comment by dummdidumm** [comment]
What do you mean by "infer the type from the default value"?
Also, this feels like something we could fix in the Svelte parser instead - feels wrong that start/end isn't set for it.

**Comment by jasonlyu123** [comment]
> What do you mean by "infer the type from the default value"?

Because of the type annotation, the type for the parameter would be any instead of inferring from the default value like functions usually do. 

> This feels like something we could fix in the Svelte parser instead. 
Sure. We can deal with this type of problem later. I can't really think of a way to let ts infer the type now.

**Comment by dummdidumm** [comment]
I pushed a fix to Svelte to make the default parameter appear correctly. What's left is the default type inference problem.

**Comment by dummdidumm** [comment]
Closing in favor of #2449

**Pull request closed without merging**
