### PR TITLE
Watch for and handle tsx/jsx files in svelte-check

### PR DESCRIPTION
**Pull request by odinhb**
#1827 

I've encountered the following error with the files under the `test/` directory in the svelte-check package:

<details>
<summary>error</summary>

```
$ node ./dist/src/index.js --workspace ./test --tsconfig ./tsconfig.json

====================================
Loading svelte-check in workspace: /home/odin/dev/svelte-language-tools/packages/svelte-check/test
Getting Svelte diagnostics...

...dev/svelte-language-tools/packages/svelte-check/test/Index.svelte:11:2
Error: Argument of type 'typeof Untyped__SvelteComponent_' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Type 'Untyped__SvelteComponent_' is missing the following properties from type 'ATypedSvelteComponent': $$prop_def, $$events_def, $$slot_def, $on

Possible causes:
- You use the instance type of a component where you should use the constructor type
- Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {} (js)

<Untyped />
<Typed />


.../dev/svelte-language-tools/packages/svelte-check/test/Index.svelte:12:2
Error: Argument of type 'typeof Typed__SvelteComponent_' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Type 'Typed__SvelteComponent_' is missing the following properties from type 'ATypedSvelteComponent': $$prop_def, $$events_def, $$slot_def, $on

Possible causes:
- You use the instance type of a component where you should use the constructor type
- Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {} (js)
<Untyped />
<Typed />


====================================
svelte-check found 2 errors and 0 warnings
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

That error seems unrelated to my code changes. (It also happens on master in the `test/` directory) But I've not been able to reproduce it in a fresh repository.

### CODE REVIEW

**Comment by odinhb** [comment]
> Thank you! Could you revert the changes to `test`? This change doesn't need coverage in my opinion, it's more meant to be a smoke test

I don't understand this. I intuited that the test directory was nothing but a smoke test, but I thought it was a bit lacking (not even a `.ts` file in there). I know I would want to have more than a single `.svelte` file in my smoke test.

I also found it quite useful to quickly run the version I was hacking on over a set of example files.

Would you mind if I moved those files to a separate directory intended for ad-hoc testing? (Seeing as there are no automated tests)

**Comment by dummdidumm** [comment]
The smoke test just ensures that `svelte-check` starts up at all and runs through without an error. All other tests with regards to type checking working correctly are inside `language-server`. Please keep the PR scoped to the jsx/tsx fix and revert the other changes. We can discuss the playground idea in a different PR.

**Comment by odinhb** [comment]
I marked this as draft because I've determined that this error:

<details>
<summary>error</summary>

```
$ yarn example
yarn run v1.22.17
$ node ./dist/src/index.js --workspace ./example --tsconfig ./tsconfig.json

====================================
Loading svelte-check in workspace: /home/odin/dev/svelte-language-tools/packages/svelte-check/example
Getting Svelte diagnostics...

/home/odin/dev/svelte-language-tools/packages/svelte-check/example/Index.svelte:11:2
Error: Argument of type 'typeof Untyped__SvelteComponent_' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Type 'Untyped__SvelteComponent_' is missing the following properties from type 'ATypedSvelteComponent': $$prop_def, $$events_def, $$slot_def, $on

Possible causes:
- You use the instance type of a component where you should use the constructor type
- Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {} (js)

<Untyped />
<Typed />


/home/odin/dev/svelte-language-tools/packages/svelte-check/example/Index.svelte:12:2
Error: Argument of type 'typeof Typed__SvelteComponent_' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Type 'Typed__SvelteComponent_' is missing the following properties from type 'ATypedSvelteComponent': $$prop_def, $$events_def, $$slot_def, $on

Possible causes:
- You use the instance type of a component where you should use the constructor type
- Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {} (js)
<Untyped />
<Typed />


====================================
svelte-check found 2 errors and 0 warnings
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

seems to be caused by my changes, but I haven't the faintest clue why.

Backporting the change to v2 doesn't cause this error.

You can find some .tar.gz files of svelte-check [here](https://github.com/odinhb/svelte-language-tools/releases). Maybe you can tell me if I've just packaged them incorrectly? In that case I'd expect my playground script not to return the error, however.

**Comment by odinhb** [comment]
I created an absolutely minimal reproduction repo [here](https://github.com/odinhb/repro-svelte-component-not-assignable)

**Comment by dummdidumm** [comment]
I can't reproduce this when building and testing this. Closing in favor of #1894

**Pull request closed without merging**
