### PR TITLE
chore: upgrade svelte-preprocess to v6

### PR DESCRIPTION
**Pull request by benmccann**
this will fix the deprecation warnings that users are getting

### CODE REVIEW

**Comment by dummdidumm** [comment]
preprocess has node 18 and Svelte 4 minimum, svelte-check has 16 and 3 - so this would be a major release. Need to check what else we want to do for svelte-check 4.0 (#2243) - @jasonlyu123 anything that springs to mind we want to change?

**Comment by benmccann** [comment]
I had just filed https://github.com/sveltejs/language-tools/issues/2391, which Jason suggested would be a breaking change

**Comment by benmccann** [comment]
@dummdidumm would you be able to give a look at https://github.com/sveltejs/svelte-preprocess/pull/645 before this PR? Then I could update this one to use it

**Comment by dummdidumm** [comment]
Closing in favor of #2452

**Pull request closed without merging**
