### PR TITLE
(fix) add field-sizing

### PR DESCRIPTION
**Pull request by tkhs0813**
closed https://github.com/sveltejs/language-tools/issues/2340

### CODE REVIEW

**Comment by tkhs0813** [comment]
@jasonlyu123 
Could you please confirm?

**Comment by jasonlyu123** [comment]
We don't usually add experiment CSS feature with limited browser support and this is an experiment property that only chromium support.

**Comment by tkhs0813** [comment]
@jasonlyu123 
Understood. In that case, are there any options to avoid this issue?

**Comment by jasonlyu123** [comment]
No. In the editor, there is a `css.customData` option but it's not available for svelte-check. But since this is a CSS property with poor browser support I'll say this is a valid warning.

**Comment by tkhs0813** [comment]
Understood. Thank you.

**Pull request closed without merging**
