### PR TITLE
Add dev tools like eslint, .editorconfig

### PR DESCRIPTION
**Pull request by jasonlyu123**
More info see the discussion of  #39 and the conclusion https://github.com/sveltejs/language-tools/pull/39#issuecomment-619376180

I moved the eslint config and .editorconfig from the main svelte repo and tune it to fit the coding style of this repo.

Does everyone have any opinion on the rules? Or what do I missed from the main repo?

this is the `eslintrc` of the main svelte repo:
https://github.com/sveltejs/svelte/blob/master/.eslintrc.js

Fix exist lint error would come later.

### CODE REVIEW

**Comment by dummdidumm** [comment]
For me it seems good.

**Comment by dummdidumm** [comment]
We also need to add it to the CI script https://github.com/sveltejs/language-tools/blob/master/.github/workflows/CI.yml

**Comment by jasonlyu123** [comment]
Good! it failed

**Comment by dummdidumm** [comment]
I think the only stuff we need to have a closer look at is the "forbidden non-null assertion"-errors, because they require some more code.

**Comment by jasonlyu123** [comment]
I am also hesitant about `@typescript-eslint/consistent-type-assertions`. The default is `assertionStyle: 'as'`. but I change it to `assertionStyle: 'angle-bracket'` as it seems we have more angle-bracket in the existing codebase

**Comment by dummdidumm** [comment]
As @orta said I would "cargo cult" the main repo here. If they use the `as` syntax, we will, too.

**Comment by orta** [comment]
Could also turn off that option - it doesn't feel like something which is a critical lint

**Comment by dummdidumm** [comment]
This looks good to me now. The non-null-assertions can be gradually resolved (or ignored) later.

**Comment by jasonlyu123** [comment]
yeap! I'll make this ready for review.
I think most of them could be fixed.
Some of them can be handled more gracefully, or just change it to optional chaining when possible.

**Comment by orta** [comment]
This looks great

**Pull request merged**
