### PR TITLE
fix comma operator in debug

### PR DESCRIPTION
**Pull request by pushkine**
#739

### CODE REVIEW

**Review by jasonlyu123 — CHANGES_REQUESTED** [review]
Thanks for your contribution. However, we might need a more complex solution on transformation for better sourcemap.

**Review by dummdidumm — APPROVED** [review]
Thanks!

**Review by dummdidumm — CHANGES_REQUESTED** [review]
Found a bug in combination with `$store` usage. `{@debug $store}` is translated to `__sveltets_store_get(myfile)}`. Notice the missing `{` at the start. I guess either the `remove` in `debug` removes it or the inner store transformation. One way to fix this could be to remove the `@debug` like it was done before and overwrite only the `,` inbetween with `}{`.

**Comment by pushkine** [comment]
It's related to the MagicString API, I have no idea how to use prepend/append left/right, using prependLeft on both seems to cover the bug you found

**Review by dummdidumm — APPROVED** [review]

**Pull request merged**
