### PR TITLE
(fix) don't trigger html completions inside moustache tags

### LINKED ISSUE #89: Autocompletion inside on:click arrowfunction
**Describe the bug**
When making event handler (i.e. on:click), the arrow function autocompletion inside seems to be malfunctioning.

**To Reproduce**
Try typing:
```
<div class="answer" on:click={() =}
```
when you do `>` it autocomplete the div inside the arrow function, see gif below:

**Expected behavior**
No autocompletion, let me do the arrow function.

**Screenshots**

[Link to imgur gif](https://imgur.com/a/zhgBEKo)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin: Svelte Beta

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #89

@jasonlyu123 does this seem like a reasonable fix for you?

### CODE REVIEW

**Comment by jasonlyu123** [comment]
I think it could be moved to `HTMLPlugin`'s `doTagComplete`. Also, there's also another thing that could trigger this tag close.
```
<input type="checkbox" checked={ a > b } />
```

Maybe using a solution similar to what you did to find last open tag to find if there is any unended  `{` before `>` . And just play it safe and disabling the auto close even if `{` or  `}` is possibly in a string literal.

**Comment by dummdidumm** [comment]
You are right with both things. Will do, thanks!

**Comment by jasonlyu123** [comment]
Find an advantage of doing it in the `HtmlPlugin`. we could utilize HTML language service's AST to find where current node start
```
const node = html.findNodeAt(offsetAt(position, document.getText()));
```

**Comment by dummdidumm** [comment]
Good find! I will try to add it to the logic.

**Comment by dummdidumm** [comment]
I did add your suggestions, works really well. Thanks again!

**Pull request merged**
