### PR TITLE
(feat) support ts 4.7 group aware organize import

### PR DESCRIPTION
**Pull request by jasonlyu123**
#1486

Added a check in the svelte2tsx to add a blank line if the import matches the import organization group in the ts 4.7. Also fixed a bug introduced when updated to ts4.7 where an empty indent would be added sometimes. Not sure if there's another way to fix it. 

We could probably use the group-aware organize import for #1508 if we add a blank line to separate module script import with instance import. Is this something we want to support?

### CODE REVIEW

**Comment by jasonlyu123** [comment]
Side note. Because of the new group-aware organize import I found some behaviour differences between Linux / Mac and Windows. This caused the test to fail when the group didn't need organizing. Maybe it's the cause of  #1269. Because we always use `\n` between the moved import. Maybe that is the reason why Typescript always think it needs organizing. 

I removed the semicolon in some tests so that it always has the edit. But maybe we should find a way to filter it out.

**Comment by dummdidumm** [comment]
Mhhm yeah how to test this? 😅  Are we able to somehow hijack reading the file during tests and insert the line breaks in a way we want?

**Comment by jasonlyu123** [comment]
Wondering if we can check the line ending on the original file. If the file is all CRLF or all LF then we use it. If the file has a mixed line ending or no line break we use the system line ending. This should at least help folks using LF in Windows and make our test more reliable. 

And then we can try to #1269 later. I tried it on a ts file and it seems like the ts extension also just applies the edit even if nothing changes. So maybe that's not that important. 

If we want to go this route do we also apply it to other ts features that accept format options? If so we probably can work around the failed test here. And do it in another PR.

**Comment by dummdidumm** [comment]
> If we want to go this route do we also apply it to other ts features that accept format options? If so we probably can work around the failed test here. And do it in another PR.

Sounds good 👍 What are other areas where we need this in? If we do need this elsewhere, we should extract the "what kind of line ending to use?"-logic into a small function (in another PR then, doesnt have to be now).

Is this PR good to merge now? Seems like you added the logic and the tests look good.

**Comment by jasonlyu123** [comment]
Yeah. We probably can extract it out later. I think it's ready to merge.

**Pull request merged**
