### PR TITLE
Wrap plugin execution in try catch

### PR DESCRIPTION
**Pull request by dummdidumm**
This way, if a plugin for whatever reason fails, it won't destroy the whole promise chain.

Happened to me when node-sass was not found, then the CSSPlugin failed, then everything failed.

### CODE REVIEW

**Comment by orta** [comment]
Yeah, this is a solid idea

**Comment by PatrickG** [comment]
But now they are executed one after the other?

**Comment by dummdidumm** [comment]
I think they still get executed in parallel. The map function has no built in way of doing "I wait for the previous item if it's a promise", so it just maps all plugins synchronously and then hands the array of promises to Promise.all, which then handles them in parallel.

**Comment by PatrickG** [comment]
Yea, you are right.
Sorry for the interruption :D

**Comment by dummdidumm** [comment]
No problem :)

**Pull request merged**
