### PR TITLE
Fix misconfigured attribute matching regex in tag extraction

### PR DESCRIPTION
**Pull request by sjafferi**
Fix bug where `extractTag` would wrongfully extract tags starting with script/style (https://github.com/sveltejs/language-tools/issues/43).

example:

```html
<styles>p{ color: blue; }</styles>
<p>bla</p>
 ></style>
```

would incorrectly match `<styles>....</style>`

### CODE REVIEW

**Comment by jasonlyu123** [comment]
Can the white space be replaced by `\s`?

**Comment by dummdidumm** [comment]
Also one could put more than one space between `<style` and tags (f.e `<style   lang="scss">`). Could you modify the regex to handle this and add a test for that? Thanks! Apart from that it look great.

**Comment by sjafferi** [comment]
> Also one could put more than one space between `<style` and tags (f.e `<style lang="scss">`). Could you modify the regex to handle this and what @jasonlyu123 said and add a test for that? Thanks! Apart from that it look great.

Sure! Just so I understand correctly, this is the case where multiple spaces are placed after `<style` and in between attributes (i.e. `<style     lang="scss">`)? If so, the current regex supports this, I've added a few test cases to ensure that. Let me know if this is what you were referring to.

**Comment by dummdidumm** [comment]
Perfect, thanks!

**Pull request merged**
