### PR TITLE
Disable console.log since it break content-length

### PR DESCRIPTION
**Pull request by mattn**
#404

### CODE REVIEW

**Comment by dummdidumm** [comment]
Oh, this is the cause of the issue? Glad you found that!
Could you elaborate a bit on what exactly you mean by "it breaks content-length"? Is there maybe another way than to just disable logging?

For the fix itself we would also need to disable `console.error` / `console.warning` I guess? Also I'd rather not just patch the console in every environment, just for `stdio`. A long-term / better alternative would be to find something that also works in stdio.

**Comment by mattn** [comment]
`--stdio` read constent from stdin and write content to stdout with content-length headers. And `console.log` also write to stdout. If you keep console.log, wrap console.log to write the content to stderr.

```
console.log = function() { console.warn.apply(console, arguments) }
```

**Comment by dummdidumm** [comment]
Hints:
- You can run `yarn lint` in the workspace to see the lint errors before pushing
- Please only do the `console.log` patching if the `stdio` command is set:
```ts
if (process.argv.includes('--stdio')) {
   console.log = ...
}
```

**Comment by mattn** [comment]
Sorry about noisy.

**Comment by dummdidumm** [comment]
No problem 😄 I'll just sqash it when merging.

**Comment by dummdidumm** [comment]
Thank you very much!

**Pull request merged**
