### PR TITLE
(chore) add debugger config for ts plugin

### PR DESCRIPTION
**Pull request by jasonlyu123**
https://github.com/microsoft/TypeScript/wiki/Debugging-Language-Service-in-VS-Code#debugging-tsserver-server-side

added an environment variable for the tsserver to launch with inspector enabled when we launch extension for debugging. So we can attach a debugger like what we did for language-server. Do we want to keep the sourcemap in the published plugin? If not, we might need to create another tsconfig to distinguish.

### CODE REVIEW

**Comment by dummdidumm** [comment]
Awesome! Good question about those source maps. I don't think that we need them in production, but it's also a question of whether or not it really hurts. How many additional kilobytes are we talking about?

**Comment by jasonlyu123** [comment]
20KB. About 25%.

**Comment by dummdidumm** [comment]
Just realized we have a `.npmignore` file. Could you add the source maps to that? Then they are not published and we don't need an extra build step.

**Review by dummdidumm — APPROVED** [review]
🎉

**Pull request merged**
