### PR TITLE
Update SvelteKit anchor tag props

### LINKED ISSUE #1680: Remove `sveltekit:prefetch` auto-completion
### Description

Typing `prefetch` on anchor tags suggests auto-completing the [removed `sveltekit:prefetch`](https://github.com/sveltejs/kit/commit/8e9839a) as well as the [new `data-sveltekit-prefetch`](https://kit.svelte.dev/docs/link-options#data-sveltekit-prefetch).

Screen Shot 2022-10-13 at 21 19 03

When selecting the new `data-sveltekit-prefetch`, it completes to an empty string:

Screen Shot 2022-10-13 at 21 19 27

### Proposed solution

Remove `sveltekit:prefetch` and complete `data-sveltekit-prefetch` to this instead:

```
<a href="foo" data-sveltekit-prefetch></a>
```

since prefetching takes no arguments.

### Alternatives

_No response_

### Additional Information, eg. Screenshots

_No response_

### PR DESCRIPTION
**Pull request by janosh**
Closes #1680.

```txt
sveltekit:noscroll -> data-sveltekit-noscroll
sveltekit:prefetch -> data-sveltekit-prefetch
sveltekit:reload -> data-sveltekit-reload
```

### CODE REVIEW

**Comment by janosh** [comment]
Not sure how to fix the 2 failing tests. Should this

```ts
interface SvelteKitAnchorProps {
    // transformed from data-sveltekit-noscroll so it should be camel case
    dataSveltekitNoscroll?: true | undefined | null;
    dataSveltekitPrefetch?: true | undefined | null;
    dataSveltekitReload?: true | undefined | null;
}
```

be this?

```ts
interface SvelteKitAnchorProps {
    // transformed from data-sveltekit-noscroll so it should be camel case
    'data-sveltekit-noscroll'?: true | undefined | null;
    'data-sveltekit-prefetch'?: true | undefined | null;
    'data-sveltekit-reload'?: true | undefined | null;
}
```

**Comment by dummdidumm** [comment]
`data-X` attributes are supported in JSX, too, so it should be fine to have them unconverted/as-is.

**Comment by janosh** [comment]
Not sure how to fix this:

```log
309 passing (7s)
  2 failing

  1) htmlx2jsx
       test/htmlx2jsx/samples/sveltekit-anchor-attrs:

      AssertionError [ERR_ASSERTION]: Expected a different output
      + expected - actual

      - { svelteHTML.createElement("a", {...__sveltets_2_empty({"data-sveltekit-noscroll":true}),}); }
      - { svelteHTML.createElement("a", {...__sveltets_2_empty({"data-sveltekit-prefetch":true}),}); }
      - { svelteHTML.createElement("a", {...__sveltets_2_empty({"data-sveltekit-reload":true}),}); }
      - { svelteHTML.createElement("a", { ...__sveltets_2_empty({"data-sveltekit-prefetch":true}),}); }
      + { svelteHTML.createElement("a", {"data-sveltekit-noscroll":true,}); }
      + { svelteHTML.createElement("a", {"data-sveltekit-prefetch":true,}); }
      + { svelteHTML.createElement("a", {"data-sveltekit-reload":true,}); }
      + { svelteHTML.createElement("a", { "data-sveltekit-prefetch":true,}); }
      
      at /home/runner/work/language-tools/language-tools/packages/svelte2tsx/test/helpers.ts:322:20
      at Context.<anonymous> (test/helpers.ts:111:17)
      at processImmediate (internal/timers.js:461:21)

  2) svelte2tsx
       test/svelte2tsx/samples/svelte-element:

      AssertionError [ERR_ASSERTION]: Expected a different output
      + expected - actual

        { svelteHTML.createElement("tag", { });}
        { svelteHTML.createElement(tag ? 'a' : 'b', {  });}
        { svelteHTML.createElement(tag, { });tag; }
        { svelteHTML.createElement(tag, {    "on:click":() => tag,});}
      - { svelteHTML.createElement('a', {    ...__sveltets_2_empty({"data-sveltekit-prefetch":true}),"href":`[https://kit.svelte.dev`](https://kit.svelte.dev%60/),});}};
      + { svelteHTML.createElement('a', {    "data-sveltekit-prefetch":true,"href":`[https://kit.svelte.dev`](https://kit.svelte.dev%60/),});}};
       return { props: {}, slots: {}, getters: {}, events: {} }}
       
       export default class Input__SvelteComponent_ extends __sveltets_1_createSvelte2TsxComponent(__sveltets_1_partial(__sveltets_1_with_any_event(render()))) {
       }
      
      at /home/runner/work/language-tools/language-tools/packages/svelte2tsx/test/helpers.ts:322:20
      at Context.<anonymous> (test/helpers.ts:111:17)
```

**Comment by janosh** [comment]
> I am also wondering if we should remove the old one from `SvelteKitAnchorProps`. That could a problem for those still using the old version.

Seems ok to me. Breaking changes were what people using SvelteKit early signed up for.

**Comment by janosh** [comment]
> We probably need to add an exception if we want to type-check it.

@jasonlyu123 Could you elaborate? Should the `expected` be updated?

https://github.com/sveltejs/language-tools/blob/282df009fe6a212d171725f0d23feb5ad16578d2/packages/svelte2tsx/test/htmlx2jsx/samples/sveltekit-anchor-attrs/expectedv2.js#L4

Or the actual changed?

**Comment by jasonlyu123** [comment]
The `__sveltets_2_empty` call is for not type check `data-` attribute. If you want it to be type-checked, the if statement I linked needs to be tweaked. Otherwise, you could just update the expected. I think I prefer the former, but also ok if we go with the latter.

**Comment by janosh** [comment]
Thanks for finishing @dummdidumm! 👍

**Pull request merged**
